# Generated by Django 4.2.4 on 2023-08-23 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Protocols",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, default="blbl", max_length=200, null=True
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("method", models.TextField(blank=True, max_length=1000, null=True)),
                ("file", models.FileField(blank=True, null=True, upload_to="uploads")),
            ],
        ),
        migrations.CreateModel(
            name="ChatResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, default="blbl", max_length=200, null=True
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("method", models.TextField(blank=True, max_length=1000, null=True)),
                (
                    "protocol",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="protocolsapp.protocols",
                    ),
                ),
            ],
        ),
    ]
