# Generated by Django 4.2.4 on 2023-11-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("protocolsapp", "0002_delete_chatresponse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protocols",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
