# Generated by Django 4.2.4 on 2023-11-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("protocolsapp", "0003_alter_protocols_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protocols",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="uploads"),
        ),
    ]
