# Generated by Django 4.2.4 on 2023-10-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_user_followers_user_following_user_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
    ]
