# Generated by Django 4.2.1 on 2023-08-19 18:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samplesapp", "0002_samplesmodel_species"),
    ]

    operations = [
        migrations.AddField(
            model_name="samplesmodel",
            name="remained",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
