# Generated by Django 4.2.1 on 2023-08-19 22:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samplesapp", "0003_samplesmodel_remained"),
    ]

    operations = [
        migrations.AlterField(
            model_name="samplesmodel",
            name="quantity",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="samplesmodel",
            name="remained",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
