# Generated by Django 4.2.1 on 2023-08-20 15:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("samplesapp", "0005_alter_samplesmodel_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="samplesmodel",
            name="quantity",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="samplesmodel",
            name="remained",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.CreateModel(
            name="SampleUsageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_used", models.DateField(auto_now_add=True)),
                (
                    "quantity_used",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("description", models.TextField()),
                (
                    "sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="samplesapp.samplesmodel",
                    ),
                ),
            ],
        ),
    ]
