# Generated by Django 4.2.1 on 2023-08-20 15:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samplesapp", "0006_alter_samplesmodel_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sampleusagemodel",
            name="quantity_used",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
