# Generated by Django 4.2.4 on 2023-10-30 12:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("samplesapp", "0007_alter_sampleusagemodel_quantity_used"),
    ]

    operations = [
        migrations.AlterField(
            model_name="samplesmodel",
            name="remained",
            field=models.IntegerField(
                blank=True,
                default=1,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
