# Generated by Django 4.2.4 on 2023-11-27 11:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("samplesapp", "0009_alter_samplesmodel_remained"),
        ("samplesapp", "0009_alter_samplesmodel_sample_date"),
    ]

    operations = []
