# Generated by Django 3.2.18 on 2023-08-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reagents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reagent_name', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=200)),
                ('firm', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('number', models.DecimalField(decimal_places=2, max_digits=5)),
                ('expiration_date', models.DateTimeField()),
                ('purchase_date', models.DateTimeField()),
                ('description', models.TextField()),
            ],
        ),
    ]
