# Generated by Django 3.2.18 on 2023-08-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagentsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reagents',
            name='number',
        ),
        migrations.AddField(
            model_name='reagents',
            name='cat_number',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='reagents',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reagents',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reagents',
            name='firm',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reagents',
            name='owner',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reagents',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
