# Generated by Django 3.2.18 on 2023-08-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagentsapp', '0002_auto_20230815_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reagents',
            name='cat_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
