# Generated by Django 4.2.1 on 2023-08-17 21:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reagentsapp", "0003_alter_reagents_cat_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="reagents",
            name="quantity",
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="reagents",
            name="unit",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
