# Generated by Django 4.2.1 on 2023-08-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reagentsapp", "0004_reagents_quantity_reagents_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reagents",
            name="unit",
            field=models.CharField(
                choices=[
                    ("ml", "ml"),
                    ("ul", "ul"),
                    ("g", "g"),
                    ("mg", "mg"),
                    ("szt", "sztuk"),
                ],
                default="ml",
                max_length=5,
            ),
        ),
    ]
