# Generated by Django 4.2.1 on 2023-08-17 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reagentsapp", "0007_alter_reagents_unit"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reagents",
            old_name="used",
            new_name="remained",
        ),
    ]
