# Generated by Django 4.2.1 on 2023-08-17 23:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reagentsapp", "0008_rename_used_reagents_remained"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reagents",
            name="remained",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
