# Generated by Django 4.2.4 on 2023-08-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reagentsapp", "0009_alter_reagents_remained"),
    ]

    operations = [
        migrations.AddField(
            model_name="reagents",
            name="access_key",
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
    ]
