# Generated by Django 4.2.4 on 2023-10-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reagentsapp", "0010_reagents_access_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reagents",
            name="unit",
            field=models.CharField(
                choices=[
                    ("-", "-"),
                    ("ml", "ml"),
                    ("ul", "ul"),
                    ("g", "g"),
                    ("mg", "mg"),
                    ("ug", "ug"),
                    ("szt", "sztuk"),
                ],
                default="-",
                max_length=5,
            ),
        ),
    ]
