# Generated by Django 4.2.4 on 2023-11-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reagentsapp", "0011_alter_reagents_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reagents",
            name="unit",
            field=models.CharField(
                choices=[
                    ("-", "-"),
                    ("ml", "ml"),
                    ("μl", "μl"),
                    ("g", "g"),
                    ("mg", "mg"),
                    ("μg", "μg"),
                    ("ug", "ug"),
                    ("szt", "sztuk"),
                ],
                default="-",
                max_length=5,
            ),
        ),
    ]
